// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekpumpitqanmmjpgpeiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrcHVtcGl0cWFubW1qcGdwZWl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwODkwMTksImV4cCI6MjA3NDY2NTAxOX0.3oxlEZRpfWKpOICsvyg7hPruHYr2cS7ljop3mPizpO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);