// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jeyxcpfhzydsfnsccgnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpleXhjcGZoenlkc2Zuc2NjZ253Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NTA3OTIsImV4cCI6MjA1ODEyNjc5Mn0.2AzKI6Vd-uAJ5IOI1VYqpFCwHwh_m3x3r8yT37VyJn4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);